# Generated by Django 4.1 on 2022-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0002_alter_curso_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateTimeField(),
        ),
    ]
